name: Push to Anaconda Cloud

on:
  push:
    branches:
    - "master"

jobs:
  push-environment:
    name: Push environment to Anaconda Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
          python-version: 3.x
          auto-activate-base: true
      - name: Install dependencies
        run: |
          conda install anaconda-client conda-build
          conda config --set anaconda_upload yes
      - name: build env info
        run: |
          conda info
          conda list
      - name: push
        env: # Or as an environment variable
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          ANACONDA_USER: ClimateImpactLab
        run: |
          anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USER risingverse.yml
