name: Test conda environment

on:
  schedule:
    - cron: "* * * * 1"  # Every Monday.
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test-environment:
    name: Test conda environment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "risingverse"
          environment-file: risingverse.yml
          auto-activate-base: false
          auto-update-conda: true
      - name: conda info
        run: |
          conda info -a
          conda list
